#!/bin/bash

echo "=== Updating system ==="
sudo apt update -y

echo "=== Installing Docker ==="
sudo apt install -y docker.io docker-compose git

echo "enable and start docker"
sudo systemctl start docker
sudo systemctl enable docker

echo "Allow ubuntu to run docker"
sudo usermod -aG docker ubuntu

echo "clone app repo and cd into folder"
git clone https://github.com/lucystevenson/tech515-docker-app-project8.git repo
cd repo


echo "stop containers and remove volumes (to allow reseeding)"
docker-compose down -v

echo " build and run containers"
docker-compose up -d