#!/bin/bash

echo "=== Updating system ==="
apt update -y

echo "=== Installing Docker ==="
apt install -y docker.io docker-compose git

echo "enable and start docker"
systemctl start docker
systemctl enable docker

echo "Allow ubuntu to run docker"
sudo usermod -aG docker ubuntu

echo "clone app repo and cd into folder"
git clone https://github.com/lucystevenson/tech515-docker-app-project8.git
cd tech515-docker-app-project8


echo "stop containers and remove volumes (to allow reseeding)"
docker compose down -v

echo " build and run containers"
docker compose up -d